Lambda-School-Labs/homerun-fe

- package.json
- src/utils/AxiosWithAuth.js
> Axios with auth

- src/components/dashboard/TodoList.js
>  added Icons

- src/components/auth/Confirm-Account.js
- src/utils/Routes.js
> fixed route typo

- src/components/auth/Confirm-Account.js
> added useEffect

- package-lock.json
- src/SASS/Header.scss
- src/components/auth/Confirm-Account.js
- src/components/auth/Reset-Password.js
- src/components/dashboard/AssignUserButton.js
- src/components/dashboard/Todo.js
- src/components/dashboard/TodoList.js
> Working through an array error

- package-lock.json
- package.json
- src/actions/index.js
- src/actions/userActions.js
- src/components/dashboard/todos/TodoList.js
- src/components/household/AddChild.js
- src/components/household/List.js
- src/configRedux.js
- src/index.js
- src/reducers/index.js
- src/reducers/userReducer.js
> Setting up redux

- .env
- src/actions/todoActions.js
- src/components/dashboard/Dashboard.js
- src/components/dashboard/todos/Todo.js
- src/components/dashboard/todos/TodoList.js
- src/index.js
- src/reducers/todoReducer.js
> Rescheduling

- src/components/dashboard/todos/Todo.js
- src/components/header/Header.js
> fixed merge errors

- src/App.js
- src/actions/userActions.js
- src/components/auth/SignIn-Email.js
- src/components/dashboard/todos/ControlTodo.js
- src/components/dashboard/todos/Todo.js
- src/components/dashboard/todos/TodoList.js
- src/components/header/Header.js
- src/components/settings/HouseholdSettings.js
- src/components/sidebar/Sidebar.js
- src/reducers/userReducer.js
Child only has access to the dashboard and cannot edit todos - only able to mark them as complete
Child was able to have full control over the todos before now they have limited control
> Child view

- src/actions/todoActions.js
- src/components/dashboard/todos/ControlTodo.js
- src/components/dashboard/todos/Todo.js
- src/hooks/useAsyncState.js
- src/reducers/todoReducer.js
> Reschedule operational. Requires useEffect and time modifications

- src/SASS/Sidebar.scss
- src/components/header/Header.js
- src/components/sidebar/Sidebar.js
Changed the sidebar menu to navlinks and moved the logout button to the bottom right.
> Sidebar navlinks

- src/components/dashboard/todos/TodoList.js
> Attemping to reset again

- src/SASS/Header.scss
- src/components/account/Account.js
- src/components/account/AccountForm.js
- src/components/account/ChildAccountDropdown.js
- src/components/dashboard/todos/TodoList.js
- src/components/header/Header.js
- src/components/household/Household.js
- src/components/settings/AccountSettings.js
- src/components/sidebar/Sidebar.js
- src/utils/Routes.js
Updates the account view to include the child account dropdown and limits the todos visible on the dashboard when logged in as a child to only the todos assigned to said child.
> Account view & child dashboard restrictions

- src/components/sidebar/Sidebar.js
> fixed icon naming error

- package.json
- src/components/dashboard/todos/Todo.js
- src/index.js
- src/utils/DatePicker.js
> Created new DatePicker and new logic

- src/components/dashboard/todos/Todo.js
- src/components/dashboard/todos/TodoEditModal.js
- src/scss/TodoList.scss
Adds a modal to edit an existing todo's title.
- Last minute smoke test
> Edit todo title functionality

- src/components/marketing/AboutUsDraft.js
> Marketing adding icons

- src/components/marketing/AboutUsDraft.js
Reverts Lambda-School-Labs/homerun-fe#89
> Revert "Marketing adding icons"

- .github/workflows/nodejs.yml
- package.json
- src/components/dashboard/todos/ControlTodo.js
- src/components/marketing/AboutUsDraft.js
- src/scss/TodoList.scss
> Adding code climate test

- src/App.js
- src/components/auth/Forgot-Password.js
- src/components/auth/SignUp.js
- src/components/auth/SignUpForm.js
- src/components/dashboard/Categories/Tab.js
- src/components/dashboard/todos/ControlTodo.js
- src/components/dashboard/todos/Todo.js
- src/components/dashboard/todos/TodoEditModal.js
- src/components/header/Header.js
- src/components/sidebar/Sidebar.js
- src/components/sidebar/Sidebar.spec.js
Working through code climate code smells.
> Code smells zt

- src/App.js
- src/components/auth/Forgot-Password.js
- src/components/auth/SignUp.js
- src/components/dashboard/Categories/Tab.js
- src/components/dashboard/todos/ControlTodo.js
- src/components/dashboard/todos/Todo.js
- src/components/dashboard/todos/TodoEditModal.js
- src/components/header/Header.js
- src/components/sidebar/Sidebar.js
Mostly removing un-used imports. Also going to be some prettier syntax changes.
> Imports cleanup

- README.md
> Private ENV Section

- src/components/marketing/ContactUsForm.js
I designed the component to be responsive to all breakpoints. It has been converted to a pure component and now uses useState to manage the form data. I introduced Axios as the HTTP client.
> Contact Redesign

- src/components/marketing/AboutUs.js
- src/components/marketing/Card.js
- src/scss/hexagon.scss
- uploaded missing About us pages
Previous PR had missing pages
> [FIX] About Us / Reworked pages

- src/components/marketing/AboutUs.js
- src/components/marketing/Card.js
- src/scss/hexagon.scss
- shaped group member as hexagon shape
> [FEATURE] About page / Hexagon

- src/components/marketing/AboutUs.js
- src/components/marketing/Card.js
- src/components/marketing/ContactUsForm.js
- src/scss/hexagon.scss
- tweaked to make spacing & centering better
> [STYLE] Consistency / Spacing & centering

- src/components/layout/Navigation.spec.js
- src/components/marketing/AboutUs.js
Reworked tests now take into account button click even by utilizing window pathname instead of trying to rely on router
> Fixed tests to take into account navigation link click events

- package-lock.json
- package.json
- src/actions/houseHoldActions.js
- src/actions/houseHoldActions.spec.js
- src/actions/todoActions.js
- src/actions/todoActions.spec.js
- src/actions/userActions.js
- src/actions/userActions.spec.js
- src/components/auth/SignUp.js
Adds tests for redux action creators
> Finished household actions and added return statements to redux

- src/components/marketing/Home.js
- src/components/marketing/Home.spec.js
- [x ] Complete, tested, ready to review and merge
- [x ] I have performed a self-review of my own code
- [ x] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [x ] There are no merge conflicts
> Home unit test

- .codeclimate.yml
Fixes codeclimate metrics used to judge maintainability, into more reasonable restrictions for Javascript
Only seen on backend repository as of yet
> Add codeclimate config file

- src/components/marketing/ContactUsForm.js
- src/components/marketing/ContactUsForm.spec.js
Contact form connected to new /contact endpoint
> Contact form connected to new /contact endpoint

- src/components/marketing/ContactUsForm.js
ContactUsForm updated (bug fixed)
> ContactUsForm updated

- src/components/auth/SignUp.js
- src/components/auth/SignUpPartTwo.js
- src/components/auth/useForm.js
- src/components/auth/validate.js
> Pin feature

- .github/workflows/nodejs.yml
- package-lock.json
- src/components/auth/SignUp-Test.spec.js
Fixes actions not starting due to out-of-date branch references
- GitHub actions integration
> Fix actions yml

- src/components/auth/SignUp.js
- src/components/auth/SignUpPartTwo.js
- src/components/auth/useForm.js
- src/components/auth/validate.js
…nt with the previous existing validations
> Form validation

- package-lock.json
- src/components/auth/SignIn-Landing.js
- src/components/auth/SignUp.js
- src/components/auth/SignUp.spec.js
- src/components/auth/SignUpPartTwo.js
- src/components/auth/SignUpPartTwo.spec.js
- src/components/dashboard/todos/Todo.js
- src/components/marketing/AboutUs.js
> add testing to SignUpPartTwo and remove some react warnings

- package-lock.json
- src/actions/houseHoldActions.js
- src/actions/houseHoldActions.spec.js
- src/components/dashboard/todos/TodoList.js
- src/components/household/InviteConfirm.js
- src/components/household/InviteConfirm.spec.js
- src/utils/Routes.js
Fixes issues with backend compatibility, due to certain necessary changes on the backend.
- Jest tests and local behavior
> Compatibility with backend

- src/components/auth/SignUp.js
- src/components/auth/useForm.js
> Reverted changes

- src/utils/permissions.js
Adds a file of exported constants to simplify synchronous changes made on the front-end regarding permissions
Completed, could afford more description later on.
No tests necessary.
> Permission file

- src/components/auth/SignIn-Landing.js
- src/components/auth/SignUp.js
Due to a git bug, the signup component wasn't pushed to github. This PR includes the new code.
> fix signup component

- src/components/household/InviteConfirm.js
- src/components/household/InviteMember.js
- src/components/household/inviteUseForm.js
- src/components/household/inviteValidation.js
- src/utils/Routes.js
> Permission level fe

- src/App.js
- src/components/dashboard/todos/Todo.js
- src/components/dashboard/todos/TodoList.js
- src/reducers/userReducer.js
- src/reducers/userReducer.spec.js
Adds conditional rendering and functionality to the Todo component based on user's permission level
- Local server running the frontend and existing Jest tests
> Todo perms

- src/App.js
- src/actions/houseHoldActions.js
- src/components/dashboard/todos/TodoList.js
- src/components/header/Header.js
- src/components/household/EditPermissions.js
- src/components/household/EditUserForm.js
- src/components/household/List.js
- src/components/household/List.spec.js
- src/components/household/editUseForm.js
- src/components/household/permissionValidation.js
- src/scss/EditPermissions.scss
- src/scss/Household.scss
- src/scss/index.scss
Adds permission edit field in households tab, and conditionally render components depending on permission level
- Jest tests and local server
> Edit permission level fe

- src/components/household/InviteMember.js
- src/components/household/InviteMember.spec.js
- [x ] New feature (non-breaking change which adds functionality)
- [x ] I have performed a self-review of my own code
> Invite member test

- src/actions/categoriesActions.js
- src/actions/index.js
- src/actions/todoActions.js
- src/components/auth/SignIn-Landing.js
- src/components/auth/SignUp.js
- src/components/dashboard/Categories/CategoryAddModal.js
- src/components/dashboard/Categories/CategoryEditModal.js
- src/components/dashboard/Categories/CategoryList.js
- src/components/dashboard/Categories/CategoryTabs.js
- src/components/dashboard/Dashboard.js
- src/components/dashboard/Dashboard.spec.js
- src/components/dashboard/todos/ControlTodo.js
- src/components/dashboard/todos/ControlTodo.spec.js
- src/components/dashboard/todos/Todo.js
- src/components/household/Household.js
- src/reducers/categoriesReducer.js
- src/reducers/index.js
- src/scss/Household.scss
Tests ControlTodo Component
- [ x ] Test
- [x ] Complete, tested, ready to review and merge
Locally
> Control todo test

- src/components/marketing/Home.js
> new home description and feature info

- src/components/dashboard/Categories/CategoryList.js
- src/scss/Household.scss
- src/scss/InviteMember.scss
> minor styling adjustments for consistency

- src/actions/todoActions.js
- src/components/dashboard/todos/ControlTodo.js
- src/components/dashboard/todos/Todo.js
- src/components/marketing/ContactUsForm.js
Fixes due date appearing under a todo even when one is not assigned. Also remove some console logging of environment variables (serious security risk!)
- Local server
> Fix due date bug
